version: '1'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
