export default [
	{
		name: 'JavaScript Burger',
		description: '100% carne bovina, alface, tomate, cebola, picles e queijo',
		overview: 'Hambúrguer favorito de todos os tempos',
		price: 20.99,
		category: 'sandwich',
	},
	{
		name: 'Python Burger',
		description:
			'100% carne bovina, queijo cheddar, cebolas crocantes e molho BBQ',
		overview: 'Explosão de sabor agridoce de churrasco',
		price: 22.99,
		category: 'sandwich',
	},
	{
		name: 'Java Burger',
		description:
			'100% carne bovina, queijo suíço, cogumelos e cebolas refogadas',
		overview: 'Combinação saborosa de cogumelos e queijo',
		price: 24.99,
		category: 'sandwich',
	},
	{
		name: 'Vegetarian Burger',
		description: 'Hambúrguer vegetariano, alface, tomate, cebola e picles',
		overview: 'Deliciosa opção vegetariana',
		price: 18.99,
		category: 'sandwich',
	},
	{
		name: 'Swift Burger',
		description: 'Peito de frango grelhado, alface, tomate e maionese',
		overview: 'Hambúrguer de frango suculento',
		price: 19.99,
		category: 'sandwich',
	},
	{
		name: 'Fish and Chips Burger',
		description: 'Filé de peixe empanado, alface, tomate e molho tártaro',
		overview: 'Hambúrguer de peixe crocante',
		price: 21.99,
		category: 'sandwich',
	},
	{
		name: 'PHP Bacon Cheeseburger',
		description: '100% carne bovina, queijo cheddar e bacon',
		overview: 'Hambúrguer clássico com bacon',
		price: 23.99,
		category: 'sandwich',
	},
	{
		name: 'C++ Double Cheeseburger',
		description: 'Dois hambúrgueres de carne bovina e queijo',
		overview: 'Hambúrguer duplo com queijo',
		price: 26.99,
		category: 'sandwich',
	},
	{
		name: 'Ruby Jalapeño Burger',
		description:
			'100% carne bovina, queijo cheddar, jalapeños e molho especial',
		overview: 'Pedaços picantes de jalapeño',
		price: 25.99,
		category: 'sandwich',
	},
	{
		name: 'Go Avocado Burger',
		description: '100% carne bovina, abacate, alface, tomate e molho especial',
		overview: 'Toque de abacate refrescante',
		price: 27.99,
		category: 'sandwich',
	},
	{
		name: 'French Fries',
		description: 'Batatas fritas crocantes',
		overview: 'Clássico e irresistível',
		price: 8.99,
		category: 'side',
	},
	{
		name: 'Onion Rings',
		description: 'Anéis de cebola empanados',
		overview: 'Crocante e saboroso',
		price: 12.99,
		category: 'side',
	},
	{
		name: 'Mozzarella Sticks',
		description: 'Palitos de queijo empanados',
		overview: 'Queijo derretido empanado',
		price: 14.99,
		category: 'side',
	},
	{
		name: 'Sweet Potato Fries',
		description: 'Batatas doces fritas crocantes',
		overview: 'Opção saudável e saborosa',
		price: 10.99,
		category: 'side',
	},
	{
		name: 'Garlic Bread',
		description: 'Pão francês com alho e manteiga',
		overview: 'Pão com sabor de alho',
		price: 9.99,
		category: 'side',
	},
	{
		name: 'Caesar Salad',
		description: 'Alface romana, croutons, queijo parmesão e molho Caesar',
		overview: 'Salada clássica e deliciosa',
		price: 16.99,
		category: 'side',
	},
	{
		name: 'Coleslaw',
		description: 'Salada de repolho e cenoura com molho especial',
		overview: 'Opção leve e refrescante',
		price: 8.99,
		category: 'side',
	},
	{
		name: 'Chili Cheese Fries',
		description: 'Batatas fritas com queijo e chili',
		overview: 'Batatas fritas cobertas com chili',
		price: 18.99,
		category: 'side',
	},
	{
		name: 'Chocolate Cake',
		description: 'Bolo de chocolate molhado',
		overview: 'Sabor intenso de chocolate',
		price: 14.99,
		category: 'dessert',
	},
	{
		name: 'Apple Pie',
		description: 'Torta de maçã com canela',
		overview: 'Sabor clássico e caseiro',
		price: 12.99,
		category: 'dessert',
	},
	{
		name: 'Cheesecake',
		description: 'Torta de queijo cremosa',
		overview: 'Sabor delicado e cremoso',
		price: 16.99,
		category: 'dessert',
	},
	{
		name: 'Brownie Sundae',
		description: 'Brownie com sorvete e calda de chocolate',
		overview: 'Combinação irresistível de sabores',
		price: 18.99,
		category: 'dessert',
	},
	{
		name: 'Milkshake',
		description: 'Bebida cremosa e refrescante',
		overview: 'Sabor clássico de baunilha',
		price: 10.99,
		category: 'dessert',
	},
	{
		name: 'Coca-Cola',
		description: 'Refrigerante tradicional de cola',
		overview: 'Refrescante e clássico',
		price: 5.99,
		category: 'drink',
	},
	{
		name: 'Guaraná Antarctica',
		description: 'Refrigerante sabor guaraná',
		overview: 'Bebida brasileira tradicional',
		price: 6.99,
		category: 'drink',
	},
	{
		name: 'Água Mineral',
		description: 'Água mineral sem gás',
		overview: 'Hidratação saudável',
		price: 4.99,
		category: 'drink',
	},
	{
		name: 'Suco Natural',
		description: 'Suco de frutas natural',
		overview: 'Sabor refrescante e saudável',
		price: 8.99,
		category: 'drink',
	},
	{
		name: 'Chá Gelado',
		description: 'Chá gelado com limão',
		overview: 'Bebida refrescante e saudável',
		price: 7.99,
		category: 'drink',
	},
	{
		name: 'Cerveja',
		description: 'Cerveja Pilsen nacional',
		overview: 'Bebida alcoólica clássica',
		price: 9.99,
		category: 'drink',
	},
	{
		name: 'Caipirinha',
		description: 'Cachaça, limão e açúcar',
		overview: 'Bebida alcoólica brasileira',
		price: 14.99,
		category: 'drink',
	},
	{
		name: 'Mojito',
		description: 'Rum, hortelã e limão',
		overview: 'Bebida alcoólica refrescante',
		price: 16.99,
		category: 'drink',
	},
	{
		name: 'Gin Tônica',
		description: 'Gin, água tônica e limão',
		overview: 'Bebida alcoólica aromática',
		price: 18.99,
		category: 'drink',
	},
	{
		name: 'Milkshake',
		description: 'Saboroso milkshake de chocolate',
		overview: 'Cremoso, doce, e saboroso',
		price: 12.0,
		category: 'drink',
	},
];
